---
ui:
  service:
    externalPort: 9292
    internalPort: 9292

  image:
    repo: alxbird/ui
    tag: latest

  postHost:
  postPort:
  commentHost:
  commentPort:

comment:
  service:
    externalPort: 9292
    internalPort: 9292

  image:
    repo: alxbird/comment
    tag: latest

  databaseHost:

post:
  service:
    externalPort: 5000
    internalPort: 5000

  image:
    repo: alxbird/post
    tag: latest

  databaseHost:
...
