---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "get.fullname" . }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: secret-{{ .Release.Name }}-{{ .Chart.Name }}
  backend:
    serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
    servicePort: {{ .Values.service.externalPort }}
