---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "get.fullname" . }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: reddit
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        name: ui
        env:
          - name: ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
