version: '3'

services:

  post_db:

    networks:
      reddit:
        aliases:
          - ${COMMENT_DATABASE_HOST}
          - ${POST_DATABASE_HOST}
  ui:

    #volumes:
    #  - ./ui:/app

    environment:
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      COMMENT_SERVICE_HOST: ${COMMENT_SERVICE_HOST}

    command: puma -w 2 --debug

  post:

    networks:
      reddit:
        aliases:
          - ${POST_SERVICE_HOST}

    #volumes:
    #  - ./post-py:/app

    environment:
      POST_DATABASE_HOST: ${POST_DATABASE_HOST}

  comment:

    #volumes:
    #  - ./comment:/app

    networks:
      reddit:
        aliases:
          - ${COMMENT_SERVICE_HOST}

    environment:
      COMMENT_DATABASE_HOST: "${COMMENT_DATABASE_HOST}"

    command: puma -w 2 --debug
