---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment-deployment
  labels:
    app: reddit
    component: post
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: post
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: post
    spec:
      containers:
      - image: alxbird/comment
        name: comment
